### ISSUE TITLE
Problem running example

### ISSUE THREAD

**Issue by danperazzo** [google/stereo-magnification#18]
Hello, thanks for putting the code here on github. I have been trying to run the examples, however I have got the following error: `Error reported to Coordinator: <type 'exceptions.ValueError'>, Can't load save_path when it is None.
Traceback (most recent call last):
  File "./mpi_from_images.py", line 362, in <module>
    tf.app.run()
  File "/home/daniel/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/daniel/.local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/daniel/.local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./mpi_from_images.py", line 282, in main
    saver.restore(sess, ckpt_file)
  File "/home/daniel/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1274, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
`

**Comment by park-youngjae** [comment]
Did you solve the problem?
