### ISSUE TITLE
Fail to train VGG loss

### ISSUE THREAD

**Issue by yzxing87** [google/stereo-magnification#30]
Hi, 

I can sucessfully train the pixel loss but failed at VGG loss (output images are black). The command I used to train VGG loss is 

> python train.py --cameras_glob=RealEstate10K/sample_dataset/camera_params/train/*txt  \ 
--image_dir=RealEstate10K/sample_dataset/train --experiment_name=debug_vgg_loss --which_loss=vgg --batch_size=4 \ 
--vgg_model_file=imagenet-vgg-verydeep-19.mat --learning_rate=5e-5

The loss seems to descent normally. During the training process, most output images visualized by tensorboard are black while some are normal. I have tried to adjust different learning rates (1e-4, 5e-5, etc.) but it is still not working. Is there any special guideline to train the vgg loss? Thanks.

**Comment by Richerhooders** [comment]
Hello, I'd like to ask you that I always make mistakes when using vgg loss:
Traceback (most recent call last):
  File "train.py", line 95, in <module>
    tf.app.run()
  File "/root/miniconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 89, in main
    FLAGS.learning_rate, FLAGS.beta1, FLAGS.vgg_model_file)
  File "/home/HCM/stereo-magnification-master/stereomag/mpi.py", line 285, in build_train_graph
    grads_and_vars = optim.compute_gradients(total_loss, var_list=train_vars)
UnboundLocalError: local variable 'total_loss' referenced before assignment
How can I solve this problem？

**Comment by Richerhooders** [comment]
I have the same problem as you. Have you solved it?
